#! /bin/sh

case "$#" in
1 )	;;
* )	echo "Usage: $0 version" >&2 ;exit 1 ;;
esac

mkdir /global/ices/www/site/eugridpma/distribution/$1
rsync -rav accredited worthless others accredited.in /global/ices/www/site/eugridpma/distribution/$1/
echo "This is version $1" > /global/ices/www/site/eugridpma/distribution/$1/version.txt
