#! /bin/sh

for i in "$@" 
do
  caname=`echo $i |sed -e 's/.*\/ca_//;s/-[^-]*-[^-]*\.noarch\.rpm$//'`

  if [ -d $caname ] ; then
    echo $caname already done
    continue
  fi

  mkdir temp$$
  rpm2cpio $i | ( cd temp$$ ; cpio -i -d ; mv etc/grid-security/certificates/* . ; rm -r etc )
  mv temp$$ $caname
  hash=`openssl x509 -hash -noout -in $caname/*.0`

  echo "$caname" >> $caname/$hash.alias

done
