#!/bin/sh


if [ x"$1" = x"" -o x"$2" = x"" ]; then
  echo "Usage: $0 BASEDIR VERSION" >&2 ; exit 1
fi

BASEDIR=$1
VERSION=$2

if [ ! -d $BASEDIR/accredited -o ! -d $BASEDIR/others ]; then
  echo "This script, $0, must be run in the repository directory" >&2
  exit 1
fi

DVERSION=$VERSION

# Absolute directory for top of redhat mirror
MIRRORDIR=$BASEDIR
# Absolute directory for top of apt repository
APTDIR=$BASEDIR/apt
# URL of repository
ORIGINURL=http://www.eugridpma.org/distribution/$DVERSION/apt

rm -r $APTDIR
mkdir -p $APTDIR/base
# Create the main release file
cat >$APTDIR/base/release <<EOF
Origin: $ORIGINURL
Label: EUGridPMA Distribution $VERSION
Suite: EUGridPMA Distribution $VERSION
Architectures: noarch
Components: accredited others
Description: APT repository of EUGridPMA distribution $VERSION
EOF


# ACCREDITED
# Create the release file
cat >$APTDIR/base/release.accredited <<EOF
Archive: stable
Component: accredited
Version: $VERSION
Origin: $ORIGINURL
Label: EUGridPMA Distribution Accredited CAs $VERSION
Architecture: noarch
EOF

# Remove old symlink to rpm directory and Create new symlink to rpm directory
rm -rf $APTDIR/RPMS.accredited
mkdir -p $APTDIR/RPMS.accredited
ln -s $MIRRORDIR/*.noarch.rpm $MIRRORDIR/accredited/RPMS/*.rpm $APTDIR/RPMS.accredited

# Generate apt index
genbasedir --bloat $APTDIR accredited



# OTHERS
# Create the release file
cat >$APTDIR/base/release.others <<EOF
Archive: stable
Component: others
Version: $VERSION
Origin: $ORIGINURL
Label: EUGridPMA Distribution Accredited CAs $VERSION
Architecture: noarch
EOF

# Remove old symlink to rpm directory and Create new symlink to rpm directory
rm -rf $APTDIR/RPMS.others
mkdir -p $APTDIR/RPMS.others
ln -s $MIRRORDIR/others/RPMS/*.rpm $APTDIR/RPMS.others

# Generate apt index
genbasedir --bloat $APTDIR others



###########
genbasedir --hashonly $APTDIR accredited others

cat > $APTDIR/README.txt <<EOF
APT repository for EUGridPMA Distribution $VERSION
-----------------------------------------------------------------------------

This repository contains the Accredited and Other CA trust anchor
distribution from the EUGridPMA. PLEASE NOTE that only those
CAs contained in the "RPMS.accredited/" subdirectory are compliant with
the minimum requirements. The "RPMS.others/" is distribution for
informational purposes only.

Add the following to your "/etc/apt/sources.list.d/eugridpma.list" file:

  rpm http://www.eugridpma.org distribution/$VERSION/apt accredited

and run apt-get update && apt-get install ca_policy_eugridpma

EOF

