Package: ca-policy-igtf-@COLLECTION@
Version: @VERSION@-@RELEASE@
Architecture: all
Maintainer: David Groep <davidg@eugridpma.org>
Installed-Size: 1
@DEBREQUIRED@@DEBCONFLICTS@@DEBREPLACES@Section: net
Priority: optional
Homepage: http://www.eugridpma.org/
Description: IGTF-accredited @COLLECTION@ authority policy set
 This package contains the description and list of all @COLLECTION@
 accredited authorities, as well as an install time dependency on
 the packages providing these trust anchors
